version: "3.9"
services:

  spring-boot:
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    build: .

  postgres:
    image: postgres:14.4-alpine
    environment:
      POSTGRES_DB: "bistro_db"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: