INSERT INTO ingredient (name, type) VALUES ('Diced Tomatoes', 'VEGGIES');
INSERT INTO ingredient (name, type) VALUES ('Lettuce', 'VEGGIES');
INSERT INTO ingredient (name, type) VALUES ('Cheddar', 'CHEESE');
INSERT INTO ingredient (name, type) VALUES ('Monterrey Jack', 'CHEESE');
INSERT INTO ingredient (name, type) VALUES ('Salsa', 'SAUCE');
INSERT INTO ingredient (name, type) VALUES ('Sour Cream', 'SAUCE');
INSERT INTO ingredient (name, type) VALUES ('Flour Tortilla', 'WRAP');
INSERT INTO ingredient (name, type) VALUES ('Corn Tortilla', 'WRAP');
INSERT INTO ingredient (name, type) VALUES ('Ground Beef', 'PROTEIN');
INSERT INTO ingredient (name, type) VALUES ('Carnitas', 'PROTEIN');